CREATE SCHEMA IF NOT EXISTS DM
	AUTHORIZATION sfakhrutdinov;

DROP TABLE IF EXISTS dm.dm_account_turnover_f;
CREATE TABLE IF NOT EXISTS dm.dm_account_turnover_f(
	on_date DATE
	,account_rk BIGINT
	,credit_amount NUMERIC(23,8)
	,credit_amount_rub NUMERIC(23,8)
	,debet_amount NUMERIC(23,8)
	,debet_amount_rub NUMERIC(23,8)
	,PRIMARY KEY (on_date, account_rk)
);

CREATE TABLE IF NOT EXISTS dm.dm_account_balance_f(
	on_date date
	,account_rk int
	,balance_out double precision
	,balance_out_rub double precision
);

ALTER TABLE dm.dm_account_balance_f ADD PRIMARY KEY (on_date, account_rk);
ALTER TABLE dm.dm_account_balance_f ALTER COLUMN on_date SET NOT NULL;
ALTER TABLE dm.dm_account_balance_f ALTER COLUMN account_rk SET NOT NULL;

CREATE TABLE IF NOT EXISTS dm.dm_f101_round_f(
	FROM_DATE DATE
	,TO_DATE DATE
	,CHAPTER CHAR(1)
	,LEDGER_ACCOUNT CHAR(5)
	,CHARACTERISTIC CHAR(1)
	,BALANCE_IN_RUB NUMERIC(23,8)
	,R_BALANCE_IN_RUB NUMERIC(23,8)
	,BALANCE_IN_VAL NUMERIC(23,8)
	,R_BALANCE_IN_VAL NUMERIC(23,8)
	,BALANCE_IN_TOTAL NUMERIC(23,8)
	,R_BALANCE_IN_TOTAL NUMERIC(23,8)
	,TURN_DEB_RUB NUMERIC(23,8)
	,R_TURN_DEB_RUB NUMERIC(23,8)
	,TURN_DEB_VAL NUMERIC(23,8)
	,R_TURN_DEB_VAL NUMERIC(23,8)
	,TURN_DEB_TOTAL NUMERIC(23,8)
	,R_TURN_DEB_TOTAL NUMERIC(23,8)
	,TURN_CRE_RUB NUMERIC(23,8)
	,R_TURN_CRE_RUB NUMERIC(23,8)
	,TURN_CRE_TOTAL NUMERIC(23,8)
	,R_TURN_CRE_TOTAL NUMERIC(23,8)
	,BALANCE_OUT_RUB NUMERIC(23,8)
	,R_BALANCE_OUT_RUB NUMERIC(23,8)
	,BALANCE_OUT_VAL NUMERIC(23,8)
	,R_BALANCE_OUT_VAL NUMERIC(23,8)
	,BALANCE_OUT_TOTAL NUMERIC(23,8)
	,R_BALANCE_OUT_TOTAL NUMERIC(23,8)
);